---
abstract: 'A web front end to a simple, extensible Perl debugger'
author:
  - 'Leon Brocard, C<< <acme@astray.com> >>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-ebug-HTTP
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst: '5.64'
  Catalyst::DispatchType::Regex: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::View::TT: 0
  Devel::ebug: '0.45'
  HTML::Prototype: 0
  PPI: '1.110'
  PPI::HTML: 0
  Path::Class: 0
  Test::Expect: 0
  Test::WWW::Mechanize::Catalyst: 0
resources:
  bugtracker: https://github.com/plicease/Devel-ebug-HTTP/issues
  homepage: https://metacpan.org/pod/Devel::ebug::HTTP
  license: http://dev.perl.org/licenses/
  repository: https://github.com/plicease/Devel-ebug-HTTP
version: '0.32'
