---
name: Devel-ebug-HTTP
version: 0.29
author:
  - 'Leon Brocard, C<< <acme@astray.com> >>'
abstract: 'A web front end to a simple, extensible Perl debugger'
license: perl
requires:
  Catalyst: 5.10
  Catalyst::Plugin::Static: 0.07
  Catalyst::View::TT: 0.11
  Devel::ebug: 0.45
  HTML::Prototype: 0
  List::Util: 0
  PPI: 1.003
  PPI::HTML: 0
  PPI::Lexer: 0
  Path::Class: 0
  Storable: 0
  Template: 0
  Test::Expect: 0
  Test::More: 0
  Test::WWW::Mechanize::Catalyst: 0.31
provides:
  Devel::ebug::HTTP:
    file: lib/Devel/ebug/HTTP.pm
    version: 0.29
  Devel::ebug::HTTP::View::TT:
    file: lib/Devel/ebug/HTTP/TT.pm
generated_by: Module::Build version 0.2611
